### ISSUE TITLE
Compression is failing

### ISSUE THREAD

**Issue by JannikZed** [rossigee/backups#9]
I get the following error when using `compress_only` 
```
INFO:root:Compressing '/var/tmp/db.sql'...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/backups/main.py", line 63, in run
    dumpfiles = source.dump_and_compress(self.stats)
  File "/usr/lib/python3.8/site-packages/backups/sources/source.py", line 37, in dump_and_compress
    compressed_filename = backups.compress.compress(filename)
  File "/usr/lib/python3.8/site-packages/backups/compress.py", line 18, in compress
    raise BackupException("Error while compressing: %s" % errmsg)
backups.exceptions.BackupException: Error while compressing: b'gzip: unrecognized option: fast\nBusyBox v1.31.1 () multi-call binary.\n\nUsage: gzip [-cfkdt123456789] [FILE]...\n\nCompress FILEs (or stdin)\n\n\t-1..9\tCompression level\n\t-d\tDecompress\n\t-t\tTest file integrity\n\t-c\tWrite to stdout\n\t-f\tForce\n\t-k\tKeep input files\n'
```

**Comment by rossigee** [comment]
The error message suggests it's using arguments to 'gzip' which the BusyBox gzip doesn't accept.

I've only tested it on Alpine and Ubuntu, and IIRC Busybox uses it's own versions of some binaries (like 'gzip'?) with certain restrictions which is probably what's causing this. I suspect if you just remove the '--fast' argument to 'gzip' here, it would work in your case:

https://github.com/rossigee/backups/blob/master/backups/compress.py#L11
